services:
  mongodb:
    image: mongo:7.0.40-jammy
    container_name: kit-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: